apiVersion: apps/v1
kind: Deployment
metadata:
  name: phac-backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phac-backstage
  template:
    metadata:
      labels:
        app: phac-backstage
    spec:
      serviceAccountName: controller
      containers:
      - name: backstage-container
        image: northamerica-northeast2-docker.pkg.dev/river-sonar-415120/backstage/backstage:latest
        ports:
        - name: http
          containerPort: 7007